package com.sysmetrics.app.domain.export

import com.sysmetrics.app.data.model.advanced.ExportData
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import timber.log.Timber
import java.io.File
import java.util.Locale

/**
 * Human-readable text format exporter.
 * Generates formatted reports with summary and detailed logs.
 */
class TxtMetricsExporter : MetricsExporter {
    
    override val format = "TXT"
    override val mimeType = "text/plain"
    override val fileExtension = "txt"
    
    override suspend fun export(data: ExportData, outputFile: File): Result<File> {
        return withContext(Dispatchers.IO) {
            try {
                val content = generateContent(data)
                outputFile.writeText(content)
                Timber.d("TXT export successful: ${outputFile.absolutePath}")
                Result.success(outputFile)
            } catch (e: Exception) {
                Timber.e(e, "TXT export failed")
                Result.failure(e)
            }
        }
    }
    
    override fun generateContent(data: ExportData): String = buildString {
        val meta = data.metadata
        val summary = data.summary
        
        // Header
        appendLine("═".repeat(55))
        appendLine("SysMetrics Pro - Performance Report")
        appendLine("Generated: ${meta.generatedAt}")
        appendLine("Duration: ${meta.durationSeconds} seconds")
        appendLine("═".repeat(55))
        appendLine()
        
        // Device Info
        appendLine("DEVICE INFORMATION:")
        appendLine("─".repeat(55))
        appendLine("  Device: ${meta.deviceModel}")
        appendLine("  Android: ${meta.androidVersion}")
        appendLine("  App Version: ${meta.appVersion}")
        appendLine()
        
        // Summary Statistics
        appendLine("SUMMARY STATISTICS:")
        appendLine("─".repeat(55))
        
        // CPU
        appendLine("CPU Usage")
        appendLine("  Average:   ${formatFloat(summary.cpu.average)}%")
        appendLine("  Min:       ${formatFloat(summary.cpu.min)}%")
        appendLine("  Max:       ${formatFloat(summary.cpu.max)}%")
        appendLine("  Peak Time: ${summary.cpu.peakAt}")
        appendLine()
        
        // RAM
        appendLine("RAM Usage")
        appendLine("  Average:   ${formatFloat(summary.ram.average)} MB")
        appendLine("  Min:       ${formatFloat(summary.ram.min)} MB")
        appendLine("  Max:       ${formatFloat(summary.ram.max)} MB")
        appendLine("  Peak Time: ${summary.ram.peakAt}")
        appendLine()
        
        // Temperature
        if (summary.temperature.max > 0) {
            appendLine("Temperature")
            appendLine("  Average:   ${formatFloat(summary.temperature.average)}°C")
            appendLine("  Min:       ${formatFloat(summary.temperature.min)}°C")
            appendLine("  Max:       ${formatFloat(summary.temperature.max)}°C")
            appendLine("  Peak Time: ${summary.temperature.peakAt}")
            appendLine()
        }
        
        // Network
        appendLine("Network Traffic")
        appendLine("  Ingress Peak: ${formatFloat(summary.networkIngress.max)} Mbps (${summary.networkIngress.peakAt})")
        appendLine("  Egress Peak:  ${formatFloat(summary.networkEgress.max)} Mbps (${summary.networkEgress.peakAt})")
        appendLine()
        
        // FPS
        summary.fps?.let { fps ->
            appendLine("FPS")
            appendLine("  Average:   ${formatFloat(fps.average)} fps")
            appendLine("  Min:       ${formatFloat(fps.min)} fps")
            appendLine("  Max:       ${formatFloat(fps.max)} fps")
            appendLine()
        }
        
        // Detailed Log
        appendLine("═".repeat(55))
        appendLine("DETAILED LOG:")
        appendLine("─".repeat(55))
        
        data.dataPoints.takeLast(100).forEach { point ->
            val time = point.timestamp.substringAfter("T").substringBefore("Z").take(8)
            append("[$time] ")
            append("CPU: ${formatFloat(point.cpuPercent)}%, ")
            append("RAM: ${point.ramMb}MB, ")
            if (point.tempCelsius > 0) append("Temp: ${formatFloat(point.tempCelsius)}°C, ")
            append("Net: ↓${formatFloat(point.netIngressMbps)}M↑${formatFloat(point.netEgressMbps)}M")
            if (point.fps > 0) append(", FPS: ${point.fps}")
            appendLine()
        }
        
        appendLine()
        appendLine("═".repeat(55))
        appendLine("Total Data Points: ${meta.dataPointsCount}")
        appendLine("Report generated by SysMetrics Pro")
        appendLine("═".repeat(55))
    }
    
    private fun formatFloat(value: Float): String = String.format(Locale.US, "%.1f", value)
}
